version: "2.2"
services:
  db:
    image: postgres

    networks:
      - test_network

    environment:
      POSTGRES_PASSWORD: password
      
    volumes:
      - ${HOME}/data/postgresql:/var/lib/postgresql/data      


  elm-dev:
    container_name: elm-dev

    build:
      context: ./build
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    volumes:
      - ./data:/data

    networks:
      - test_network

networks:
  test_network:

