version: "2.2"
services:

  elasticsearch:
    image: elasticsearch:6.6.0

    container_name: elasticsearch

    ports:
      - "9200:9200"
      # - "9300:9300"

    environment:
      # - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      
    volumes:
      - esdata:/usr/share/elasticsearch/data

    networks:
      - esnet

  elasticsearch2:
    image: elasticsearch:6.6.0

    container_name: elasticsearch2

    # ports:
    #   - "9200:9200"
    #   - "9300:9300"

    environment:
      # - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"

    volumes:
      - esdata2:/usr/share/elasticsearch/data

    networks:
      - esnet


  kibana:
    image: kibana:6.6.0

    container_name: kibana

    ports:
      - "5601:5601"

    # volumes:
    #   - ./contents/kibana/settings:/usr/share/kibana/config

    networks:
      - esnet


  logstash:
    image: logstash:6.6.0

    container_name: logstash

    # volumes:
    #   - ./contents/logstash/pipeline:/usr/share/logstash/pipeline
    #   - ./contents/logstash/settings:/usr/share/logstash/config

    networks:
      - esnet


volumes:
  esdata:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
