version: "2.2"
services:

  elasticsearch:
    image: elasticsearch:6.6.0

    container_name: elasticsearch

    ports:
      - "9200:9200"
      - "9300:9300"

    environment:
      - discovery.type=single-node
      
    volumes:
      - esdata:/usr/share/elasticsearch/data

    networks:
      - esnet


  kibana:
    image: kibana:6.6.0

    container_name: kibana

    ports:
      - "5601:5601"

    # volumes:
    #   - ./data/kibana/settings:/usr/share/kibana/config

    networks:
      - esnet


  logstash:
    image: logstash:6.6.0

    container_name: logstash

    # volumes:
    #   - ./data/logstash/pipeline:/usr/share/logstash/pipeline
    #   - ./data/logstash/settings:/usr/share/logstash/config

    networks:
      - esnet


volumes:
  esdata:
    driver: local

networks:
  esnet:
